sudo: required
services:
  - docker

before_install:
  - docker build -t arkarmintun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arkarmintun/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'docker-react'
  env: 'DockerReact-env-1'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-658014195524'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
