sudo: required
services:
  - docker

before_install:
  - docker build -t arkarmintun/docker-react -f Dockerfile.dev .

script:
  - docker run arkarmintun/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'react-docker-travis'
  env: 'ReactDockerTravis-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-658014195524'
  bucket_path: 'react-docker-travis'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
